# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\varfolomey\Desktop\terver_lab5_2\dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EnterDialog(object):
    def setupUi(self, EnterDialog):
        EnterDialog.setObjectName("EnterDialog")
        EnterDialog.resize(642, 370)
        EnterDialog.setMinimumSize(QtCore.QSize(600, 300))
        font = QtGui.QFont()
        font.setPointSize(12)
        EnterDialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(EnterDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(EnterDialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.intervalAmountBox = QtWidgets.QSpinBox(EnterDialog)
        self.intervalAmountBox.setMinimum(5)
        self.intervalAmountBox.setMaximum(10)
        self.intervalAmountBox.setObjectName("intervalAmountBox")
        self.verticalLayout.addWidget(self.intervalAmountBox)
        self.label_2 = QtWidgets.QLabel(EnterDialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.intervalsTable = QtWidgets.QTableWidget(EnterDialog)
        self.intervalsTable.setObjectName("intervalsTable")
        self.intervalsTable.setColumnCount(0)
        self.intervalsTable.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.intervalsTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.intervalsTable.setVerticalHeaderItem(1, item)
        self.intervalsTable.horizontalHeader().setDefaultSectionSize(125)
        self.intervalsTable.verticalHeader().setDefaultSectionSize(80)
        self.intervalsTable.verticalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.intervalsTable)
        self.buttonBox = QtWidgets.QDialogButtonBox(EnterDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(EnterDialog)
        self.buttonBox.accepted.connect(EnterDialog.accept)
        self.buttonBox.rejected.connect(EnterDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(EnterDialog)

    def retranslateUi(self, EnterDialog):
        _translate = QtCore.QCoreApplication.translate
        EnterDialog.setWindowTitle(_translate("EnterDialog", "Ввести интервальный ряд"))
        self.label.setText(_translate("EnterDialog", "Количество интервалов"))
        self.label_2.setText(_translate("EnterDialog", "Интервальный ряд"))
        item = self.intervalsTable.verticalHeaderItem(0)
        item.setText(_translate("EnterDialog", "xi, xi+1"))
        item = self.intervalsTable.verticalHeaderItem(1)
        item.setText(_translate("EnterDialog", "ni"))
