# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogGrouped.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialogGruupped(object):
    def setupUi(self, dialogGruupped):
        dialogGruupped.setObjectName("dialogGruupped")
        dialogGruupped.resize(647, 300)
        dialogGruupped.setMinimumSize(QtCore.QSize(647, 300))
        dialogGruupped.setMaximumSize(QtCore.QSize(647, 300))
        font = QtGui.QFont()
        font.setPointSize(12)
        dialogGruupped.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(dialogGruupped)
        self.gridLayout.setObjectName("gridLayout")
        self.grouppedLabel = QtWidgets.QLabel(dialogGruupped)
        self.grouppedLabel.setObjectName("grouppedLabel")
        self.gridLayout.addWidget(self.grouppedLabel, 0, 0, 1, 2)
        self.countGrouped = QtWidgets.QSpinBox(dialogGruupped)
        self.countGrouped.setProperty("value", 5)
        self.countGrouped.setObjectName("countGrouped")
        self.gridLayout.addWidget(self.countGrouped, 1, 0, 1, 2)
        self.grouppedSeriesLabel = QtWidgets.QLabel(dialogGruupped)
        self.grouppedSeriesLabel.setObjectName("grouppedSeriesLabel")
        self.gridLayout.addWidget(self.grouppedSeriesLabel, 2, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(dialogGruupped)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        self.gridLayout.addWidget(self.tableWidget, 3, 0, 1, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(dialogGruupped)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 4, 1, 1, 1)

        self.retranslateUi(dialogGruupped)
        self.buttonBox.accepted.connect(dialogGruupped.accept)
        self.buttonBox.rejected.connect(dialogGruupped.reject)
        QtCore.QMetaObject.connectSlotsByName(dialogGruupped)

    def retranslateUi(self, dialogGruupped):
        _translate = QtCore.QCoreApplication.translate
        dialogGruupped.setWindowTitle(_translate("dialogGruupped", "Dialog"))
        self.grouppedLabel.setText(_translate("dialogGruupped", "Количество значений СВ:"))
        self.grouppedSeriesLabel.setText(_translate("dialogGruupped", "Группированный ряд:"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("dialogGruupped", "xi"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("dialogGruupped", "ni"))
